# Generated by Django 5.1.6 on 2025-05-07 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_brand_informations_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='ad_legacy',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='brand_info',
        ),
        migrations.AddField(
            model_name='advertisinglegacy',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertising_legacy', to='api.brand'),
        ),
        migrations.AddField(
            model_name='brandinfo',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_info', to='api.brand'),
        ),
    ]
